// <auto-generated />
namespace CloudProjectTracking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class equipment_documentfiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(equipment_documentfiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201904231616261_equipment_documentfiles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
